GIVMK/GIVMK/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomePageView
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url('', include('clientes.urls')),
    url('', include('catalogo.urls')),
    url('', include('inventario.urls')),
    url('', include('core.urls')),
    url('', include('user.urls')),
]

# Truco para poder ver ficheros multimedia con el DEBUG=TRUE
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom titles para el admin
admin.site.site_header = 'Manejo Inventario MAry Kay'
#  admin.site.index_title = 'No se que poner XD'
admin.site.site_title = 'Administrador MK'

GIVMK/clientes/urls.py
from .views import CustomerListView, ClientCreateView, ClientDeleteView
from django.urls import path, include

urlpatterns = [
    path('customersList/', CustomerListView.as_view(), name='customersList' ),
    path('addClient/', ClientCreateView.as_view(), name='addClient' ),
    path('deleteClient/<int:pk>/', ClientDeleteView.as_view(), name='deleteClient' ),
]

GIVMK/core/urls.py
from .views import HomePageView
# from .views import ClientUpdateView, ClientDetailView
from django.urls import path, include

urlpatterns = [
    path('dashboard/', HomePageView.as_view(), name='dashboard' ),
    # path('addClient/', ClientCreateView.as_view(), name='addClient' ),
    # path('deleteClient/<int:pk>/', ClientDeleteView.as_view(), name='deleteClient' ),
    # path('updateClient/<int:pk>/', ClientUpdateView.as_view(), name='updateClient' ),
    # path('detailClient/<int:pk>/', ClientDetailView.as_view(), name='detailClient' ),
]

GIVMK/clientes/models.py
from django.db import models
from core.models import  Base, BasePerson, BasePhone
from django.utils.translation import gettext_lazy as _
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill
from django.forms import model_to_dict
from datetime import date
from GIVMK.settings import MEDIA_URL, STATIC_URL

# Create your models here.
def custom_upload_to(instance, filename):
    '''Este metodo elimina de nuestra base de datos una imagen
    de una instancia se esta ya tenia una imagen previa'''
    # Obtiene la imagen antigua de la instancia en cuestion
    old_instance = Client.objects.get(pk=instance.pk)
    # Borra la imagen de la que se ha seleccionado
    old_instance.foto.delete()
    return 'Clientes/%Y/%m/%d' + filename

class Client(BasePerson):
    NIT = models.CharField('NIT', max_length=15, blank=True, null=True)
    estado = models.BooleanField('Estado', default=True)
    img = models.ImageField(
        upload_to='Clientes/%Y/%m/%d', null=True, blank=True, verbose_name='Avatar')
    # campo que creara la imagen en thubnail
    img_thubmnail = ImageSpecField(
        source='img',
        processors=[ResizeToFill(100, 100)],
        format='JPEG',
        options={'quality': 100})

    def toJSON(self):
        item = model_to_dict(self)
        item['nombre'] = self.getFullName()
        item['edad'] = self.edad()
        item['img'] = self.get_img()
        return item

    def phoneFav(self):
        for p in PhoneClient.objects.filter(client_id=self.id):
            if  p.is_favorite:
                return p.phone_number

    def get_img(self):
        if self.img_thubmnail:
            return '{}{}'.format(MEDIA_URL, self.img_thubmnail)
        return '{}{}'.format(STATIC_URL, 'core/img/NoImg.png')

    class Meta:
        verbose_name = _('Client')
        verbose_name_plural = _('Customers')

    def getFullName(self):
        return '%s %s' % (self.firts_name, self.last_name)

    def __str__(self):
        return self.getFullName()

    def clean(self):
        pass

GIVMK/core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from GIVMK.settings import AUTH_USER_MODEL
from datetime import date
from crum import get_current_user


# Create your models here.
GENDER_CHOICES = [
    ('M', _('Male')),
    ('F', _('Female')),
]

class Base(models.Model):
    userCreate = models.ForeignKey(
        AUTH_USER_MODEL, verbose_name=_('Creator User'), on_delete=models.PROTECT,
        related_name='userCreate%(app_label)s_%(class)s_related', blank=True, null=True)
    dateCreate = models.DateField(_('Creation date'), auto_now_add=True, blank=True, null=True)
    userUpdate = models.ForeignKey(
        AUTH_USER_MODEL, verbose_name=_('Modifier User'), on_delete=models.PROTECT,
        related_name='userUpdate%(app_label)s_%(class)s_related', blank=True, null=True)
    dateUpdate = models.DateField(_('Modification Date'), auto_now=True, blank=True, null=True)

    class Meta:
        abstract = True
        verbose_name = "Base"
        verbose_name_plural = "Bases"

    def __str__(self):
        pass

    def save(self):
        print('Se creo un nuevo producto')
        # self.calcularExistencia()
        # Guardando el user
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.userCreate = user
            else:
                self.userUpdate = user
        super(Base, self).save()

class BasePhone(Base):
    phone_number = models.CharField(_('Phone Number'), max_length=15, help_text=_('Add a phone number'))
    is_favorite = models.BooleanField(_('Favorite'), help_text=_('Check only is favorite'), default=True)

    class Meta:
        abstract = True
        verbose_name = _('Phone')
        verbose_name_plural = _('Phones')

    def __str__(self):
        return self.phone_number

class BasePerson(Base):
    firts_name = models.CharField(_('first_name'), max_length=75)
    last_name = models.CharField(_('last_name'), max_length=75, blank=True, null=True)
    gender = models.CharField(_('gender'), max_length=1, choices=GENDER_CHOICES)
    idNumber = models.CharField(_('Id Number'), max_length=75, blank=True, null=True)
    nacimiento = models.DateField('Fecha de Nacimiento', blank=True, null=True)
    tel = models.CharField(_('Phone'), max_length=75, blank=True, null=True)

    def edad(self):
        hoy = date.today()
        fechanacimiento=self.nacimiento
        edad = hoy.year - fechanacimiento.year - ((hoy.month, hoy.day) < (fechanacimiento.month, fechanacimiento.day))
        #primero restamos los años y luego restamos la comparación entre mes y día actual y mes y día de nacimiento.
        return edad

    class Meta:
        abstract = True
        verbose_name = _('BasePerson')
        verbose_name_plural = _('BasePersons')

    def __str__(self):
        return '%s %s' % (self.firts_name, self.last_name)

GIVMK/clientes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Client
from datetime import datetime

class ClienteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['autocomplete'] = 'off'
        self.fields['estado'].widget.attrs = {
            'hidden': 'true',
        }


    class Meta:
        model = Client
        fields = '__all__'
        widgets = {
            'nacimiento': forms.DateInput(format='%Y-%m-%d',
                attrs={
                'value': datetime.now().strftime('%Y-%m-%d'),
                'class': 'form-control'
                }),
            'firts_name': forms.DateInput(attrs={
                'class': 'form-control'
            }),
            'last_name': forms.DateInput(attrs={
                'class': 'form-control'
            }),
            'gender': forms.Select(attrs={
                'class': 'form-control'
            }),
            'idNumber': forms.DateInput(attrs={
                'class': 'form-control'
            }),
            'NIT': forms.DateInput(attrs={
                'class': 'form-control'
            }),
            'tel': forms.DateInput(attrs={
                'class': 'form-control'
            }),
        }

GIVMK/clientes/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from .models import Client
from .forms import ClienteForm

# Create your views here.

class CustomerListView(ListView):

    model = Client
    template_name = 'clientes/customersList.html'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Client.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = _('Listado de Clientes')
        return context

class ClientCreateView(CreateView):
    # permission_required = ['escuela.view_escuela', 'escuela.add_escuela']
    model = Client
    form_class = ClienteForm
    # fields = '__all__'
    success_url = reverse_lazy('customersList')
    url_redirect = success_url

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # Sobreescribimos el metodo POST
    def post(self, request, *args, **kwargs):
        data = {}
        # Campturamos el error
        try:
            # Verificamos que la accion que trae el request agregar
            action = request.POST['action']
            if action == 'add':
                # Obtenemos nuestro formulario
                form = self.get_form()
                if form.is_valid():
                    form.save()
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado a Ninguna Opcion'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'add'
        context['titulo'] = _('Registrar un Nuevo Cliente')
        context['lazyUrl'] = self.url_redirect
        context['contentAlert'] = _('Esta seguro de crerar este nuevo cliente')
        context['titleAlert'] = _('Crear nuevo Cliente')
        return context

class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('customersList')

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClienteForm
    template_name = 'clientes/client_form.html'
    success_url = reverse_lazy('customersList')
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'update':
                cli = Client.objects.filter(id=kwargs['pk']).get()
                cli.firts_name = request.POST['firts_name']
                cli.last_name = request.POST['last_name']
                cli.gender = request.POST['gender']
                cli.idNumber = request.POST['idNumber']
                cli.nacimiento = request.POST['nacimiento']
                cli.NIT = request.POST['NIT']
                cli.tel = request.POST['tel']
                # Validamos si trae cambio de img
                if request.FILES:
                    print('Si trae imagen')
                    cli.img = request.FILES['img']
                cli.save()
                print(cli.img)
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'update'
        context['titulo'] = _('Editar Cliente')
        context['lazyUrl'] = self.url_redirect
        context['contentAlert'] = _('Esta seguro de editar el cliente')
        context['titleAlert'] = _('Editar Cliente')
        return context

class ClientDetailView(DetailView):
    model = Client

GIVMK/clientes/templates/clientes/client_detail.html
<div class="modal-dialog modal-md modal-dialog-centered">
    <div class="modal-content">
        <div class="card border-left-dark shadow h-100">

            <div class="modal-header">
                <div class="row align-items-center">
                    <img src="{{ object.get_img }}" class="rounded-circle img-thumbnail mr-3" width="75">
                    <h5 class="mb-2 font-weight-bold text-gray-500 text-uppercase">
                        {{ object.getFullName }}
                    </h5>
                </div>
                <button type="button" class="close" data-dismiss="modal">
                    <i class="fas fa-window-close text-danger"></i>
                </button>
            </div>

            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                    <span>
                        <b><i class="fas fa-phone-square-alt"></i> Telefono: </b>
                        {{ object.tel }}
                    </span>
                    </div>
                    <div class="col-12">
                    <span>
                        <b><i class="fas fa-birthday-cake"></i></i> Cumpleanos: </b>
                        {{ object.nacimiento|date:"j F" }}
                    </span>
                    </div>
                    <div class="col-12">
                    <span>
                        <b><i class="fas fa-calendar-day"></i> Edad: </b>
                        {{ object.edad }}
                    </span>
                    </div>
                    <div class="col-12">
                    <span>
                        <b><i class="fas fa-laugh-wink"></i> Tipo de Piel: </b>
                        {{ object.edad }}
                    </span>
                    </div>
                    <div class="col-12">
                        <hr>
                        <h4 class="text-primary">
                            <i class="bi bi-bag-fill"></i></i> Comprado en el mes:
                            <b>Q. {{ object.edad|floatformat:2   }}</b>
                        </h4>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

GIVMK/clientes/templates/clientes/client_form.html
{% extends 'core/bases/form_base.html' %}
{% load i18n %}
{% load static %}

{% block titulo %}
<h6 class="m-0 font-weight-bold text-gray-800 text-uppercase">
    {% if object %}
        <i class="fas fa-user-edit"></i>
    {% else %}
        <i class="fas fa-user-plus mr-1"></i>
    {% endif %}
    {{ titulo }}
</h6>
{% endblock %}
{% block campos_form %}
    <div class="form-group col-md-6">
        <label for="id_firts_name" class="form-label">{{ form.firts_name.label }}</label>
        {{ form.firts_name }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="form-label">{{ form.last_name.label }}</label>
        {{ form.last_name }}
    </div>

    <div class="form-group col-md-6">
        <label for="" class="form-label">{{ form.gender.label }}</label>
        {{ form.gender }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="form-label">{{ form.idNumber.label }}</label>
        {{ form.idNumber }}
    </div>

    <div class="form-group col-md-4">
        <label for="" class="form-label">{{ form.nacimiento.label }}</label>
        {{ form.nacimiento }}
    </div>
    <div class="form-group col-md-4">
        <label for="" class="form-label">{{ form.NIT.label }}</label>
        {{ form.NIT }}
    </div>
    <div class="form-group col-md-4">
                    <label for="exampleFormControlFile1">{{ form.tel.label }}</label>
                    {{ form.tel }}
                </div>
{% endblock %}

GIVMK/clientes/templates/clientes/customersList.html
{% extends 'core/bases/list_base.html' %}
{% load static %}
{% block title %}Listado Clientes{% endblock %}

{% block card_titulo %}
<i class="fas fa-clipboard-list mr-1"></i>
    {{ titulo }}
{% endblock %}
{% block btn_add %}
    <a class="btn btn-primary btn-icon-split ml-auto" href="{% url 'addClient' %}">
        <span class="icon text-white">
            <i class="fas fa-user-plus"></i>
        </span>
        <span class="text">
            Registrar Nuevo Cliente
        </span>
    </a>
{% endblock %}
{% block tabla %}
<table id="listadoClientes" class="table" width="100%" cellspacing="0">
    <thead>
    <tr>
        <th>Img</th>
        <th>Nombre</th>
        <th>Edad</th>
        <th>Genero</th>
        <th>Telefono</th>
        <th>Acciones</th>
    </tr>
    </thead>
</table>
{% endblock %}

{% block mis_scripts %}
    <script src="{% static 'clientes/js/clientesList.js' %}"></script>
    <script>
        var listClient = "{% url 'customersList' %}";

        // Programamos el eliminado segun el id que traiga el boton
        function obtenerUrlDelete(dato) {
            {% for object in object_list %}
                var objeto = '{{object}}';
                var id = '{{object.id}}';
                if (id == dato) {
                    var url = '{% url 'deleteClient' object.id %}';
                    return url;
                }
            {% endfor %}
        }

        function obtenerUrlEdit(dato) {
            {% for object in object_list %}
                var objeto = '{{object}}';
                var id = '{{object.id}}';
                if (id == dato) {
                    var url = '{% url 'updateClient' object.id %}';
                    return url;
                }
            {% endfor %}
        }

        function obtenerUrlView(dato) {
            {% for object in object_list %}
                var objeto = '{{object}}';
                var id = '{{object.id}}';
                if (id == dato) {
                    var url = '{% url 'detailClient' object.id %}';
                    return url;
                }
            {% endfor %}
        }
    </script>
{% endblock %}