GIVMK/GIVMK/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomePageView
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url('', include('clientes.urls')),
    url('', include('catalogo.urls')),
    url('', include('inventario.urls')),
    url('', include('core.urls')),
    url('', include('user.urls')),
]

# Truco para poder ver ficheros multimedia con el DEBUG=TRUE
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom titles para el admin
admin.site.site_header = 'Manejo Inventario MAry Kay'
#  admin.site.index_title = 'No se que poner XD'
admin.site.site_title = 'Administrador MK'

GIVMK/catalogo/urls.py
from .views import ProductosListView, ProductoCreateView, ProductoDeleteView
from .views import ProductoUpdateView, ProductoDetailView
from django.urls import path, include

urlpatterns = [
    path('productosList/', ProductosListView.as_view(), name='productosList' ),
    path('addProducto/', ProductoCreateView.as_view(), name='addProducto' ),
    path('deleteProducto/<int:pk>/', ProductoDeleteView.as_view(), name='deleteProducto' ),
    path('updateProducto/<int:pk>/', ProductoUpdateView.as_view(), name='updateProducto' ),
    path('detailProducto/<int:pk>/', ProductoDetailView.as_view(), name='detailProducto' ),
]

GIVMK/core/urls.py
from .views import HomePageView
# from .views import ClientUpdateView, ClientDetailView
from django.urls import path, include

urlpatterns = [
    path('dashboard/', HomePageView.as_view(), name='dashboard' ),
    # path('addClient/', ClientCreateView.as_view(), name='addClient' ),
    # path('deleteClient/<int:pk>/', ClientDeleteView.as_view(), name='deleteClient' ),
    # path('updateClient/<int:pk>/', ClientUpdateView.as_view(), name='updateClient' ),
    # path('detailClient/<int:pk>/', ClientDetailView.as_view(), name='detailClient' ),
]

GIVMK/catalogo/models.py
from crum import get_current_user
from django.db import models
from django.forms.models import model_to_dict

from GIVMK.settings import MEDIA_URL, STATIC_URL

from core.models import Base

# Create your models here.


''' * Importacion que nos permite maquetar o formatear
con HTML una variable o texto para poder mostrar en el admin*'''
from django.utils.html import format_html

# Librerias de importacion de PILLOW para poder
# mostrar thubnails de las imagenes subidas al sistema*'''
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Impotamos Mark_Safe para poder mostar la img en el Admin
from django.utils.safestring import mark_safe


# Metodo para eliminar una fotografia si ya existe
# en la base de datos y evitar llenar el especio '''
def custom_upload_to(instance, filename):
    '''Este metodo elimina de nuestra base de datos una imagen
    de una instancia se esta ya tenia una imagen previa'''
    # Obtiene la imagen antigua de la instancia en cuestion
    old_instance = Producto.objects.get(pk=instance.pk)
    # Borra la imagen de la que se ha seleccionado
    old_instance.foto.delete()
    return 'Catalogo/Producto' + filename


class Producto(Base):
    nombre = models.CharField('Nombre', max_length=125)
    precio_consultora = models.DecimalField('Precio Consultora', max_digits=12, decimal_places=2)
    precio_catalogo = models.DecimalField('Precio Catalogo', max_digits=12, decimal_places=2)
    descripcion = models.TextField('Decripción', blank=True, null=True)
    img = models.ImageField(
        upload_to='Catalogo/', null=True, blank=True, verbose_name='Imagen')
    estado = models.BooleanField('Estado', default=False, editable=False)

    # campo que creara la imagen en thubnail
    img_thubmnail = ImageSpecField(
        source='img',
        processors=[ResizeToFill(100, 100)],
        format='JPEG',
        options={'quality': 60})

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def toJSON(self):
        item = model_to_dict(self, exclude=['img_thubmnail', 'img'])
        # item['nombre'] = self.nombre
        item['precio_consultora'] = format(self.precio_consultora, '.2f')
        item['precio_catalogo'] = format(self.precio_catalogo, '.2f')
        item['cantidad'] = int(self.existencia())
        item['invertido_cons'] = self.calcularMontoCosto()
        item['invertido_cat'] = self.calcularMontoVenta()
        # item['img_thubmnail'] = self.img_thubmnail
        item['img'] = self.get_img()
        item['existencia'] = int(self.existencia())
        return item

    def existencia(self):
        cantidad = 0
        from inventario.models import DetallePedido
        for p in DetallePedido.objects.filter(producto_id=self.id):
            cantidad += p.cantidad
        # Sumamos los ingresos a el inventario
        # for ingreso in IngresoDetalle.objects.filter(id_producto=self.id):
        #     cantidad += ingreso.cantidad
        # # Restamos las ventas
        # # for salida in VentaDetalle.objects(id_producto=self.id):
        # #     cantidad -= salida.cantidad
        # if VentaDetalle.objects.filter(id_producto=self.id):
        #     for venta in VentaDetalle.objects.filter(id_producto=self.id):
        #         cantidad -= venta.cantidad
        # if cantidad == 0:
        #     self.estado = False
        return cantidad

    def existenciaColor(self):
        cantidad = self.existencia()
        if cantidad == 0:
            cantidad = '--'
            color1 = '#D7142B'
            color2 = '#FF7800'
        else:
            self.estado = True
            if cantidad <= 1:
                color1 = '#D7142B'
                color2 = "#FF7800"
            elif cantidad <= 5:
                color1 = '#FF7800'
                color2 = 'yellow'
            else:
                color1 = '#009A19'
                color2 = '#8AFF00'
        self.save()
        return format_html(
            '<span style="color:' + color1 + '; font-weight: bold;' +
            ' text-shadow: 0px 0px 2px ' + color2 + ';">' +
            str(cantidad) + '</span>')

    # Sirve para mostrar la descripcion del metodo en el ADMIN
    existenciaColor.short_description = 'Existencias'

    def calcularMontoCosto(self):
        # from inventario.models import Ingreso, IngresoDetalle
        monto = 0
        # for producto in IngresoDetalle.objects.filter(id_producto=self.id):
        #     monto = monto + producto.monto_costo()
        if monto == 0:
            monto = '--'
            color1 = '#D7142B'
            color2 = '#FF7800'
        else:
            color1 = '#009A19'
            color2 = '#8AFF00'

        return format_html(
            '<span style="color:' + color1 + '; font-weight: bold;' +
            ' text-shadow: 0px 0px 2px ' + color2 + ';">Q. ' +
            str(monto) + '</span>')

    calcularMontoCosto.short_description = 'Monto Costo Inventario'

    def calcularMontoVenta(self):
        # from inventario.models import Ingreso, IngresoDetalle
        monto = 0
        # for producto in IngresoDetalle.objects.filter(id_producto=self.id):
        #     monto = monto + producto.monto_venta()
        if monto == 0:
            monto = '--'
            color1 = '#D7142B'
            color2 = '#FF7800'
        else:
            color1 = '#009A19'
            color2 = '#8AFF00'

        return format_html(
            '<span style="color:' + color1 + '; font-weight: bold;' +
            ' text-shadow: 0px 0px 2px ' + color2 + ';">Q. ' +
            str(monto) + '</span>')

    calcularMontoVenta.short_description = 'Monto Venta Inventario'

    def get_img(self):
        if self.img_thubmnail:
            return '{}{}'.format(MEDIA_URL, self.img_thubmnail)
        return '{}{}'.format(STATIC_URL, 'core/img/NoImg.png')

    def image_thub(self):
        ''' Retornara una imagen para ser mostrada en al admin
        en el catalogo del mismo, si no la encuetra coloca otra por default'''
        # Valida si se le subio imagen al material
        if self.img_thubmnail:
            # Y lo retorna en la lista de materiales
            return mark_safe(
                '<img src="{url}" width="{width}" height={height} />'.format(
                    url=self.img_thubmnail.url, width=50, height=50, ))
        # Si no encuentra mostrar una imagen generica
        else:
            # Y lo retorna en la lista de materiales
            return mark_safe(
                '<img src="{url}" width="{width}" height={height} />'.format(
                    url='/../static/core/img/no-img.jpg', width=50, height=50, ))

    # Sirve para mostrar la descripcion del metodo en el ADMIN
    image_thub.short_description = 'Imagen'

    def __str__(self):
        return '%s %s Exsitencias: %s' % (self.nombre, self.precio_catalogo, self.existencia())

GIVMK/producto/models.py
from django.db import models

# Create your models here.

GIVMK/catalogo/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto
from datetime import datetime

class ProductoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['autocomplete'] = 'off'

    class Meta:
        model = Producto
        fields = 'nombre', 'precio_consultora', 'precio_catalogo', 'descripcion', 'img'
        widgets = {
        #     'nacimiento': forms.DateInput(format='%Y-%m-%d',
        #         attrs={
        #         'value': datetime.now().strftime('%Y-%m-%d'),
        #         'class': 'form-control'
        #         }),
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nombre del Producto a Registrar'
            }),
            'precio_consultora': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '0.00',
                'aria-describedby': 'basic-addon1'
            }),
            'precio_catalogo': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '0.00'
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '3',
                'placeholder': 'Ingrese una descripcion del producto'
            }),
        #     'NIT': forms.DateInput(attrs={
        #         'class': 'form-control'
        #     }),
        #     'tel': forms.DateInput(attrs={
        #         'class': 'form-control'
        #     }),
        }

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                instance = form.save()
                data = instance.toJSON()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

GIVMK/catalogo/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from .models import Producto
from .forms import ProductoForm

# Create your views here.

class ProductosListView(ListView):

    model = Producto
    template_name = 'catalogo/producto_list.html'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Producto.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = _('Listado de Productos')
        return context

class ProductoCreateView(CreateView):
    # permission_required = ['escuela.view_escuela', 'escuela.add_escuela']
    model = Producto
    form_class = ProductoForm
    # fields = '__all__'
    success_url = reverse_lazy('productosList')
    url_redirect = success_url

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # Sobreescribimos el metodo POST
    def post(self, request, *args, **kwargs):
        data = {}
        # Campturamos el error
        try:
            # Verificamos que la accion que trae el request agregar
            action = request.POST['action']
            if action == 'add':
                # Obtenemos nuestro formulario
                form = self.get_form()
                if form.is_valid():
                    form.save()
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado a Ninguna Opcion'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'add'
        context['titulo'] = _('Registrar un Nuevo Producto')
        context['lazyUrl'] = self.url_redirect
        context['contentAlert'] = _('Esta seguro de crerar este nuevo producto')
        context['titleAlert'] = _('Crear nuevo Producto')
        return context

class ProductoDeleteView(DeleteView):
    model = Producto
    success_url = reverse_lazy('productosList')

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

class ProductoUpdateView(UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'catalogo/producto_form.html'
    success_url = reverse_lazy('productosList')
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'update':
                pro = Producto.objects.filter(id=kwargs['pk']).get()
                pro.nombre = request.POST['nombre']
                pro.precio_consultora = request.POST['precio_consultora']
                pro.precio_catalogo = request.POST['precio_catalogo']
                pro.descripcion = request.POST['descripcion']
                # Validamos si trae cambio de img
                if request.FILES:
                    print('Si trae imagen')
                    pro.img = request.FILES['img']
                pro.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'update'
        context['titulo'] = _('Editar Producto')
        context['lazyUrl'] = self.url_redirect
        context['contentAlert'] = _('Esta seguro de editar el producto')
        context['titleAlert'] = _('Editar Producto')
        return context

class ProductoDetailView(DetailView):
    model = Producto

GIVMK/producto/views.py
from django.shortcuts import render

# Create your views here.

GIVMK/catalogo/templates/catalogo/producto_detail.html
<div class="modal-dialog modal-md modal-dialog-centered">
    <div class="modal-content">
        <div class="card border-left-dark shadow h-100">

            <div class="modal-header">
                <div class="row align-items-center">
                    <img src="{{ object.get_img }}" class="rounded-circle img-thumbnail mx-3" width="150">
                    <div class="col">
                        <h5 class="mb-2 font-weight-bold text-gray-500 text-uppercase">
                            {{ object.nombre }}
                        </h5>
                    </div>
                </div>
                <button type="button" class="close" data-dismiss="modal">
                    <i class="fas fa-window-close text-danger"></i>
                </button>
            </div>

            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <div class="col-12 mb-1">
                    <span>
                        <b> <i class="bi bi-tags"></i> Precio Consultora: </b>
                        <span class="badge bg-warning p-2 text-dark">
                            <b>Q. {{ object.precio_catalogo|floatformat:"2" }}</b>
                        </span>
                    </span>
                        </div>
                        <div class="col-12 mb-1">
                    <span>
                        <b><i class="bi bi-tags-fill"></i> Precio Catalogo: </b>
                        <span class="badge bg-info p-2 text-dark">
                            <b>Q. {{ object.precio_consultora|floatformat:"2" }}</b>
                        </span>
                    </span>
                        </div>
                    </div>
                    <div class="col-4 top10">
                        <div class="col align-items-center text-info" align="center">
                            <b>Top 10 mas Vendidos</b>
                        </div>
                        <div class="col" align="center">
                            <i class="fas fa-medal text-warning" style="font-size: 3rem"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

GIVMK/catalogo/templates/catalogo/producto_form.html
{% extends 'core/bases/form_base.html' %}
{% load static %}

{% block title %}
    {% if object %}
        Editar Producto
    {% else %}
        Agregar Producto
    {% endif %}
{% endblock %}

{% block titulo %}
<h6 class="m-0 font-weight-bold text-gray-800 text-uppercase">
    <i class="bi bi-bullseye"></i>
    {{ titulo }}
</h6>
{% endblock %}

{% block campos_form %}
    <div class="form-group col-md-6">
        <label for="id_nombre" class="form-label">{{ form.nombre.label }}:</label>
        {{ form.nombre }}
    </div>
    <div class="form-group col-md-3">
        <label for="id_precio_consultora" class="form-label">{{ form.precio_consultora.label }}:</label>
        <div class="input-group">
            <span class="input-group-text" id="basic-addon1">Q. </span>
            {{ form.precio_consultora }}
        </div>
    </div>
    <div class="form-group col-md-3">
        <label for="id_precio_catalogo" class="form-label">{{ form.precio_catalogo.label }}:</label>
        <div class="input-group">
            <span class="input-group-text" id="basic-addon1">Q. </span>
            {{ form.precio_catalogo }}
        </div>
    </div>
    <div class="form-group col-12">
        <label for="id_descripcion" class="form-label">{{ form.descripcion.label }}:</label>
        {{ form.descripcion }}
    </div>
{% endblock %}

{% block mis_script %}
    <script>
        $('#id_precio_consultora').mask("###0.00", {reverse: true});
        $('#id_precio_catalogo').mask("###0.00", {reverse: true});
    </script>
{% endblock %}

GIVMK/catalogo/templates/catalogo/producto_list.html
{% extends 'core/bases/list_base.html' %}
{% load static %}
{% block title %}Listado Clientes{% endblock %}

{% block card_titulo %}
<i class="fas fa-clipboard-list mr-1"></i>
    {{ titulo }}
{% endblock %}
{% block btn_add %}
    <a class="btn btn-primary btn-icon-split ml-auto" href="{% url 'addProducto' %}">
        <span class="icon text-white">
            <svg width="1rem" height="1rem" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="layer-plus" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="svg-inline--fa fa-layer-plus fa-w-16 fa-2x"><path fill="currentColor" d="M304 144h64v64c0 8.84 7.16 16 16 16h32c8.84 0 16-7.16 16-16v-64h64c8.84 0 16-7.16 16-16V96c0-8.84-7.16-16-16-16h-64V16c0-8.84-7.16-16-16-16h-32c-8.84 0-16 7.16-16 16v64h-64c-8.84 0-16 7.16-16 16v32c0 8.84 7.16 16 16 16zm195.59 220.1l-58.54-26.53-161.19 73.06c-7.56 3.43-15.59 5.17-23.86 5.17s-16.29-1.74-23.86-5.17L70.95 337.57 12.41 364.1c-16.55 7.5-16.55 32.5 0 40l232.94 105.59c6.8 3.08 14.49 3.08 21.29 0L499.59 404.1c16.55-7.5 16.55-32.5 0-40zM12.41 275.9l232.94 105.59c6.8 3.08 14.49 3.08 21.29 0L448 299.28V280.7c-15.32 4.38-31.27 7.29-48 7.29-88.01 0-160.72-64.67-173.72-149.04L12.41 235.9c-16.55 7.5-16.55 32.5 0 40z" class=""></path></svg>
        </span>
        <span class="text">
            Registrar Nuevo Producto
        </span>
    </a>
{% endblock %}
{% block tabla %}
<table id="listadoProd" class="table" width="100%" cellspacing="0">
    <thead>
    <tr>
        <th>Img</th>
        <th class="text-center" width="40%">Nombre</th>
        <th>Consultora</th>
        <th>Catalogo</th>
        <th>Existecias</th>
        <th>Acciones</th>
    </tr>
    </thead>
</table>
{% endblock %}

{% block mis_scripts %}
    <script src="{% static 'catalogo/js/catalogoList.js' %}"></script>
    <script>
        var listClient = "{% url 'productosList' %}";

        // funcion para obtener url por dato y tipo de parametro
        function obtenerUrl(dato, accion){
            {% for object in object_list %}
                var url;
                var objeto = '{{object}}';
                var id = '{{object.id}}';
                if (id == dato) {
                    if (accion == 'eliminar'){
                        url = '{% url 'deleteProducto' object.id %}';
                    }else if (accion == 'editar'){
                        url = '{% url 'updateProducto' object.id %}';
                    }else if (accion == 'ver'){
                        url = '{% url 'detailProducto' object.id %}';
                    }
                    return url;
                }
            {% endfor %}
        }

        // Programamos el eliminado segun el id que traiga el boton
        function obtenerUrlDelete(dato) {
            {% for object in object_list %}
                var objeto = '{{object}}';
                var id = '{{object.id}}';
                if (id == dato) {
                    var url = '{% url 'deleteClient' object.id %}';
                    return url;
                }
            {% endfor %}
        }
    </script>
{% endblock %}